sounds = {
    "coin": "./sound/coin.wav",
    "jump": "./sound/jump.mp3",
    "game_over": "./sound/game_over.mp3",
    "level_complete": "./sound/level_complete.mp3",
    "door": "./sound/door.wav",
}

images = {
    "sky": "./img/sky.png",
    "restart_btn": "./img/restart_btn.png",
    "start_btn": "./img/start_btn.png",
    "exit_btn": "./img/exit_btn.png",
    "ghost": "./img/ghost.png",
    "guy11": "./img/guy11.png",
    "guy12": "./img/guy12.png",
    "guy21": "./img/guy21.png",
    "guy22": "./img/guy22.png",
    "guy3": "./img/guy3.png",
    "guy4": "./img/guy4.png",
    "dirt": "./img/dirt.png",
    "grass": "./img/grass.png",
    "blob": "./img/blob.png",
    "platform": "./img/platform.png",
    "spike": "./img/spike.png",
    "coin": "./img/coin.png",
    "exit": "./img/exit.png",
    "opened_exit": "./img/opened_exit.png",
    "platform_x": "./img/platform_x.png",
    "platform_y": "./img/platform_y.png",
    "load_btn": "./img/load_btn.png",
    "save_btn": "./img/save_btn.png",
}
